"""
Node 6: The Packager
Creates a downloadable ZIP file with README.
"""
import os
import zipfile
from datetime import datetime
from app.models.state import BuilderState
from app.utils.logger import get_logger
from app.config import settings

logger = get_logger(__name__)


def generate_readme(state: BuilderState) -> str:
    """Generate a comprehensive README for the project."""
    
    tech_stack_info = {
        "html_single": "Single HTML file with embedded CSS and JavaScript",
        "html_multi": "Multiple HTML files with shared CSS",
        "react_cdn": "React application loaded via CDN",
        "vue_cdn": "Vue application loaded via CDN"
    }
    
    readme = f"""# {state['user_query']}

**Generated by AI Builder Platform**  
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Project Overview

{state['user_query']}

## Technology Stack

- **Architecture:** {tech_stack_info.get(state['tech_stack'], state['tech_stack'])}
- **Files:** {len(state['generated_code'])} file(s)

## Files Included

"""
    
    for filename in state['generated_code'].keys():
        readme += f"- `{filename}`\n"
    
    if state['asset_manifest']:
        readme += "\n## External Dependencies\n\n"
        for asset in state['asset_manifest']:
            readme += f"- **{asset['name']}**: {asset['url']}\n"
    
    readme += """
## How to Run

1. Extract all files from this ZIP
2. Open `index.html` in your web browser
3. No build process or server required!

## Browser Compatibility

This project works in all modern browsers:
- Chrome/Edge (recommended)
- Firefox
- Safari

## Notes

"""
    
    if state.get('syntax_errors'):
        readme += "\n### ⚠️ Known Syntax Issues\n\n"
        for error in state['syntax_errors'][:3]:
            readme += f"- {error}\n"
    
    if state.get('semantic_issues'):
        readme += "\n### 💡 Recommendations\n\n"
        for issue in state['semantic_issues'][:5]:
            readme += f"- {issue}\n"
    
    readme += """
## Customization

Feel free to modify any file to suit your needs. The code is fully commented and ready to extend.

---

*This project was generated by an AI system. If you encounter any issues, you can manually edit the files as needed.*
"""
    
    return readme


def packager_node(state: BuilderState) -> BuilderState:
    """
    Node 6: Package all files into a downloadable ZIP.
    
    Creates:
    - All code files
    - README.md with instructions
    - Compressed ZIP file
    """
    logger.info("[PACKAGER] Creating downloadable package")
    
    state["current_node"] = "packager"
    
    try:
        # Create output directory
        os.makedirs(settings.OUTPUT_DIR, exist_ok=True)
        
        # Generate unique filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        zip_filename = f"{state['task_id']}_{timestamp}.zip"
        zip_path = os.path.join(settings.OUTPUT_DIR, zip_filename)
        
        # Generate README
        readme_content = generate_readme(state)
        state["readme_content"] = readme_content
        
        # Create ZIP file
        with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            # Add all code files
            for filename, code in state["generated_code"].items():
                zipf.writestr(filename, code)
            
            # Add README
            zipf.writestr("README.md", readme_content)
        
        state["zip_file_path"] = zip_path
        state["is_complete"] = True
        
        logger.info(f"[PACKAGER] Package created: {zip_filename}")
        logger.info(f"[PACKAGER] Total size: {os.path.getsize(zip_path) / 1024:.2f} KB")
        
        return state
        
    except Exception as e:
        logger.error(f"[PACKAGER] Error: {str(e)}")
        state["error_message"] = f"Packaging failed: {str(e)}"
        state["is_complete"] = True
        return state